### ISSUE TITLE
java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")

### ISSUE THREAD

**Issue by Freyert** [elastic/ansible-elasticsearch#328]
```
root@elastic0:/usr/lib# start-stop-daemon -d /usr/share/elasticsearch --start --user elasticsearch --exec /usr/share/elasticsearch/bin/elasticsearch
2017-06-30 19:27:48,556 main ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:585)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.apache.logging.log4j.core.jmx.Server.register(Server.java:389)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:167)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:541)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:258)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:206)
	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:220)
	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:197)
```

I'm getting this when running the playbook as root on a Vagrant VM running ubuntu  16.04.

This [StackOverflow answer](https://stackoverflow.com/a/16171108/456809) resolves the issue, but I'm not sure it's the best possible avenue.

Also ensuring that it happens in the playbook is important.

**Comment by Freyert** [comment]
>Specifying an Additional Policy File at Runtime
It is also possible to specify an additional or a different policy file when invoking execution of an application. This can be done via the "-Djava.security.policy" command line argument, which sets the value of the java.security.policy property. For example, if you use

`java -Djava.security.manager -Djava.security.policy=someURL SomeApp`

>where someURL is a URL specifying the location of a policy file, then the specified policy file will be loaded in addition to all the policy files that are specified in the security properties file.
Notes:

>The URL can be any regular URL or simply the name of a policy file in the current directory, as in
    `java -Djava.security.manager -Djava.security.policy=mypolicy SomeApp`
>The "-Djava.security.manager" argument ensures that the default security manager is installed, and thus the application is subject to policy checks. It is not required if the application SomeApp installs a security manager.
If you use

    `java -Djava.security.manager -Djava.security.policy==someURL SomeApp`
>(note the double equals) then just the specified policy file will be used; all the ones indicated in the security properties file will be ignored.
If you want to pass a policy file to the appletviewer, then use a "-J-Djava.security.policy" argument as follows:

    `appletviewer -J-Djava.security.policy=someURL myApplet`
>Note: The "-Djava.security.policy" policy file value will be ignored (for both java and appletviewer commands) if the "policy.allowSystemProperty" property in the security properties file is set to false. The default is true.

**Comment by Freyert** [comment]
Adding a new security policy to the templates directory and configuring the option in `jvm.options.j2`.

**Comment by gingerwizard** [comment]
@Freyert im struggling to see how this relates to the ansible role. Under what circumstances does this occuring? Are you able to provide the playbook?  Running the playbook as root shouldnt cause this as far as im aware.

**Comment by gingerwizard** [comment]
@Freyert we would expect that error would be thrown when enabling log4j tries to enable jmx monitoring which is in turn prevented by the security manager? Are you using any `es_jvm_custom_parameters` by any chance? Can you share:

1. Your jvm options file
2. Your playbook
3. The commit hash of the playbook you used

**Comment by Freyert** [comment]
@gingerwizard sorry! I'll try to find the playbook I was using. It was super basic though. Just a few master and data nodes.

**Comment by fedu** [comment]
Happened to me after upgrading from 5.5.0 -> 5.6.1 version. Uninstalling and reinstalling fixed it, didn't want to do the java.policy hack.

**Comment by gingerwizard** [comment]
@fedu do you have any `es_jvm_custom_parameters`? Do you have a playbook with which you can reproduce?

**Comment by fedu** [comment]
@gingerwizard Seems I can reproduce this. I just installed 5.5.0 and upgraded it to 5.6.1 after app data initialization had been done in 5.5.0.

Maybe some background information is in place. I'm using Windows 10 64bit pro.

It seems after the upgrade, Elastic tries to find the config from the wrong folder:
`Likely root cause: java.nio.file.NoSuchFileException: C:\Program Files\Elastic\Elasticsearch\config`

The correct folder would propably be: `C:\ProgramData\Elastic\Elasticsearch\config`

Here is the full output:
```
C:\Program Files\Elastic\Elasticsearch\bin>elasticsearch.exe
2017-09-19 21:33:52,744 main ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.nio.file.NoSuchFileException: C:\Program Files\Elastic\Elasticsearch\config
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:585)
Likely root cause: java.nio.file.NoSuchFileException: C:\Program Files\Elastic\Elasticsearch\config
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322)
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at org.apache.logging.log4j.core.jmx.Server.register(Server.java:389)
        at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:167)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
        at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:556)
        at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:261)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:206)
        at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:193)
        at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:220)
        at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:197)
        at java.nio.file.Files.readAttributes(Files.java:1737)
        at org.elasticsearch.common.logging.LogConfigurator.configureStatusLogger(LogConfigurator.java:175)
        at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
        at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:143)
        at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:122)
        at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:307)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132)
        at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
        at java.nio.file.Files.walkFileTree(Files.java:2662)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
        at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:150)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:122)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:307)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)

        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)
Refer to the log for complete error details.
```

Let me know if there is some more information I can provide for you (or some files).

**Comment by gingerwizard** [comment]
@fedu are you using the ansible role? or are you using the windows installer? i ask as this role doesn't currently support windows.

**Comment by fedu** [comment]
@gingerwizard No, just the same error, obviously caused by Elastic itself for not being able to access certain files. Thought it would help figuring this out.

**Comment by m-abramovich** [comment]
Do you have X-Pack installed?
Cause it mentions:
```
-> Downloading x-pack from elastic
[=================================================] 100%   
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission \\.\pipe\* read,write
* java.lang.RuntimePermission accessClassInPackage.com.sun.activation.registries
* java.lang.RuntimePermission getClassLoader
* java.lang.RuntimePermission setContextClassLoader
* java.lang.RuntimePermission setFactory
* java.security.SecurityPermission createPolicy.JavaPolicy
* java.security.SecurityPermission getPolicy
* java.security.SecurityPermission putProviderProperty.BC
* java.security.SecurityPermission setPolicy
* java.util.PropertyPermission * read,write
* java.util.PropertyPermission sun.nio.ch.bugLevel write
* javax.net.ssl.SSLPermission setHostnameVerifier
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@        WARNING: plugin forks a native controller        @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
This plugin launches a native controller that is not subject to the Java
security manager nor to system call filters.
-> Installed x-pack

```
