### ISSUE TITLE
Elasticsearch does not start: unknown setting [xpack.ml.enabled]

### ISSUE THREAD

**Issue by cyrilleverrier** [elastic/ansible-elasticsearch#428]
**Elasticsearch version**
6.1.1

**Role version**:
master (d7a5af8c33c5adb3aeff5d9e2caba2e2f853cd4d)

**JVM version**
openjdk version "1.8.0_161"

**OS version**
Centos 7

**Description of the problem including expected versus actual behaviour**:
Elasticsearch fails to start

**Playbook**:
es_enable_xpack: false

**Provide logs from Ansible**:
Successful run

**ES Logs**:
```
	Suppressed: java.lang.IllegalArgumentException: unknown setting [xpack.ml.enabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:312) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:276) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:135) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.node.Node.<init>(Node.java:330) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
		at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.1.1.jar:6.1.1]
	Suppressed: java.lang.IllegalArgumentException: unknown setting [xpack.security.enabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:312) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:276) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:135) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.node.Node.<init>(Node.java:330) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
		at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.1.1.jar:6.1.1]
	Suppressed: java.lang.IllegalArgumentException: unknown setting [xpack.watcher.enabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:312) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:276) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:135) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.node.Node.<init>(Node.java:330) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
		at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.1.1.jar:6.1.1]
		at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.1.1.jar:6.1.1]
```

**/etc/elasticsearch/es-master/elasticsearch.yml**
```
bootstrap.memory_lock: true
cluster.name: fsmonitoring
discovery:
    zen:
        minimum_master_nodes: 1
        ping.unicast.hosts: backend-plugins:9300
http.port: 9200
network.host: backend-plugins
node:
    data: false
    ingest: false
    master: true
node.name: master
transport.tcp.port: 9300




#################################### Paths ####################################

# Path to directory containing configuration (this file and logging.yml):


path.data: /var/lib/elasticsearch/backend-plugins-es-master

path.logs: /var/log/elasticsearch/backend-plugins-es-master

xpack.security.enabled: false


xpack.watcher.enabled: false

xpack.ml.enabled: false

xpack.graph.enabled: false
[root@backend-plugins ~]# java -version
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)
[root@backend-plugins ~]# uname -a
Linux backend-plugins 3.10.0-693.2.1.el7.x86_64 #1 SMP Wed Sep 6 20:06:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@backend-plugins ~]# ^C
[root@backend-plugins ~]# cat /etc/elasticsearch/es-master/elasticsearch.yml 

bootstrap.memory_lock: true
cluster.name: fsmonitoring
discovery:
    zen:
        minimum_master_nodes: 1
        ping.unicast.hosts: backend-plugins:9300
http.port: 9200
network.host: backend-plugins
node:
    data: false
    ingest: false
    master: true
node.name: master
transport.tcp.port: 9300




#################################### Paths ####################################

# Path to directory containing configuration (this file and logging.yml):


path.data: /var/lib/elasticsearch/backend-plugins-es-master

path.logs: /var/log/elasticsearch/backend-plugins-es-master

xpack.security.enabled: false


xpack.watcher.enabled: false

xpack.ml.enabled: false

xpack.graph.enabled: false
```

**Comment by cyrilleverrier** [comment]
Solved by PR https://github.com/elastic/ansible-elasticsearch/pull/427

**Comment by cyrilleverrier** [comment]
PR https://github.com/elastic/ansible-elasticsearch/pull/427 has been merged

**Comment by Crazybus** [comment]
@cyrilleverrier thanks for closing this. I'm still trying to catch up with all of the open issues and pull requests and little things like this really helps 👍
