### ISSUE TITLE
Unable to run elasticsearch 

### ISSUE THREAD

**Issue by arun-kumar-genx** [elastic/ansible-elasticsearch#474]
Elasticsearch version: v6.2.4
OS version: macOS Sierra

I have first install the ELK on my mac machine through "brew" then i installed the x-pack plugin and faced some issue on login , then i have removed that plugin using command "bin/elasticsearch-plugin remove --purge x-pack " now i am not able to connect elasticsearch with kibana shows the error below 

2018-07-23T11:01:26,786][INFO ][o.e.n.Node               ] [] initializing ...
[2018-07-23T11:01:26,843][INFO ][o.e.e.NodeEnvironment    ] [LA5HQ99] using [1] data paths, mounts [[/ (/dev/disk1)]], net usable_space [415.9gb], net total_space [930.3gb], types [hfs]
[2018-07-23T11:01:26,844][INFO ][o.e.e.NodeEnvironment    ] [LA5HQ99] heap size [990.7mb], compressed ordinary object pointers [true]
[2018-07-23T11:01:26,946][INFO ][o.e.n.Node               ] node name [LA5HQ99] derived from node ID [LA5HQ99LSrOXo9U08crNlQ]; set [node.name] to override
[2018-07-23T11:01:26,946][INFO ][o.e.n.Node               ] version[6.2.4], pid[1609], build[ccec39f/2018-04-12T20:37:28.497551Z], OS[Mac OS X/10.12.6/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_45/25.45-b02]
[2018-07-23T11:01:26,947][INFO ][o.e.n.Node               ] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/var/folders/lx/_rwg9l4j39v2z59qn5tjcz7c0000gp/T/elasticsearch.ksznhU57, -XX:+HeapDumpOnOutOfMemoryError, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Des.path.home=/usr/local/Cellar/elasticsearch/6.2.4/libexec, -Des.path.conf=/usr/local/etc/elasticsearch]
[2018-07-23T11:01:27,724][INFO ][o.e.p.PluginsService     ] [LA5HQ99] loaded module [aggs-matrix-stats]
[2018-07-23T11:01:27,724][INFO ][o.e.p.PluginsService     ] [LA5HQ99] loaded module [analysis-common]
[2018-07-23T11:01:27,725][INFO ][o.e.p.PluginsService     ] [LA5HQ99] loaded module [ingest-common]
[2018-07-23T11:01:27,725][INFO ][o.e.p.PluginsService     ] [LA5HQ99] loaded module [lang-expression]
[2018-07-23T11:01:27,725][INFO ][o.e.p.PluginsService     ] [LA5HQ99] loaded module [lang-mustache]
[2018-07-23T11:01:27,725][INFO ][o.e.p.PluginsService     ] [LA5HQ99] loaded module [lang-painless]
[2018-07-23T11:01:27,725][INFO ][o.e.p.PluginsService     ] [LA5HQ99] loaded module [mapper-extras]
[2018-07-23T11:01:27,725][INFO ][o.e.p.PluginsService     ] [LA5HQ99] loaded module [parent-join]
[2018-07-23T11:01:27,725][INFO ][o.e.p.PluginsService     ] [LA5HQ99] loaded module [percolator]
[2018-07-23T11:01:27,726][INFO ][o.e.p.PluginsService     ] [LA5HQ99] loaded module [rank-eval]
[2018-07-23T11:01:27,726][INFO ][o.e.p.PluginsService     ] [LA5HQ99] loaded module [reindex]
[2018-07-23T11:01:27,726][INFO ][o.e.p.PluginsService     ] [LA5HQ99] loaded module [repository-url]
[2018-07-23T11:01:27,726][INFO ][o.e.p.PluginsService     ] [LA5HQ99] loaded module [transport-netty4]
[2018-07-23T11:01:27,726][INFO ][o.e.p.PluginsService     ] [LA5HQ99] loaded module [tribe]
[2018-07-23T11:01:27,727][INFO ][o.e.p.PluginsService     ] [LA5HQ99] loaded plugin [ingest-geoip]
[2018-07-23T11:01:29,597][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown secure setting [bootstrap.password] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.2.4.jar:6.2.4]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.2.4.jar:6.2.4]
Caused by: java.lang.IllegalArgumentException: unknown secure setting [bootstrap.password] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:346) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:310) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:284) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:134) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.node.Node.<init>(Node.java:331) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.node.Node.<init>(Node.java:246) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.4.jar:6.2.4]
	... 6 more
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...38 completed.

[Process completed]

**Comment by Crazybus** [comment]
> OS version: macOS Sierra

I think you may have opened this issue in the wrong place. This is the ansible playbook which only supports linux. You haven't mentioned ansible anywhere so I'm 99% sure this is the wrong place :).

You are better of asking these sorts of questions in our [discuss forums](https://discuss.elastic.co/). 

> [2018-07-23T11:01:29,597][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown secure setting [bootstrap.password] please check that any required plugins are installed, or check the breaking changes documentation for removed settings

Before opening an issue you should try enabling the security feature in X-pack or if you aren't using that feature anymore you should remove `bootstrap.password` as stated in the error message.
