### ISSUE TITLE
Possible values for elastic02

### ISSUE THREAD

**Issue by deepakagg** [elastic/ansible-elasticsearch#590]
Hi

I am trying to setup multi-node elasticsearch setup but I can see this error inside the log files 

`[2019-07-07T01:11:09,388][WARN ][o.e.d.z.UnicastZenPing   ] [10.0.21.137-master_node] failed to resolve host [elastic02:9300]
java.net.UnknownHostException: elastic02: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0_212]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929) ~[?:1.8.0_212]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324) ~[?:1.8.0_212]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277) ~[?:1.8.0_212]
	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:1.8.0_212]
	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:1.8.0_212]
	at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:550) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:503) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:738) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.discovery.zen.UnicastZenPing.lambda$resolveHostsLists$0(UnicastZenPing.java:189) ~[elasticsearch-6.6.0.jar:6.6.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:660) [elasticsearch-6.6.0.jar:6.6.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

I guess the elastic02 is not being set by the ansible correctly inside the server environment?

**Comment by phawzy** [comment]
@deepakagg what did you do concerning the inventory and the elastic02:9300 issue ?
