### ISSUE TITLE
[7.1.1] Switching to elasticsearch-oss repo when x-pack.security is disabled

### ISSUE THREAD

**Issue by LukeRoz** [elastic/ansible-elasticsearch#602]
**Elasticsearch version**: 7.1.1

**Role version**:  410126465eb5ab6a68efeb82f1e5e02980960683

**JVM version** (`java -version`): 1.8.0

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 18.04.2 LTS

**Description of the problem including expected versus actual behaviour**:
During upgrade to Elasticsearch 7.1.1 with `es_enable_xpack: false` playbook will switch from `elasticsearch-7.x` to `elasticsearch-oss-7.x` repository and install `elasticsearch-oss` package which is not compatible with normal Elasticsearch installation. Because of that it's impossible to perform a rolling-upgrade.

There should be a flag which, when set, will prevent playbook from switching to oss repository.

**Playbook**:
Please specify the full playbook used to reproduce this issue.

**Provide logs from Ansible**:

**ES Logs if relevant**:

**Comment by jmlrt** [comment]
Hi @LukeRoz 
Thanks for this issue / PR.

Can you give me more details about your use case?
Is there any specific reason why you want to use Elasticsearch with basic license (not oss) but don't want to enable xpack?

**Comment by LukeRoz** [comment]
Hi @jmlrt 

It's impossible to perform rolling upgrade from 7.0.1 (basic) to 7.1.1 (oss) because basic and oss installations are not compatible with each other. Also, we want to start using x-pack in the near future, so switching to oss repo and then reverting to basic is simply inconvenient.

**Comment by jmlrt** [comment]
Why don't you set `es_enable_xpack=true`? You should have some 7.1.1 basic installation and as long as [`es_xpack_features`](https://github.com/elastic/ansible-elasticsearch/blob/812faf9596587ba438f9dacff89b9c8ce4fb6657/defaults/main.yml#35) and authentication related variable (`es_users`, `es_roles`, `es_api_basic_auth_username` & `es_api_basic_auth_password`) are empty, you won't have any impacts.

**Comment by jmlrt** [comment]
Also this role already manage switching from oss to basic repo and vice versa by handling uninstall of old package and repository change ([here](https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/elasticsearch-Debian.yml#L10-L30) and [here](https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/elasticsearch-Debian.yml#L54-L56) for Debian, [here](https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/elasticsearch-RedHat.yml#L32-L36) and [here](https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/elasticsearch-RedHat.yml#L21-L26) for Red Hat).

We currently have [oss-to-xpack-upgrade test](https://github.com/elastic/ansible-elasticsearch/blob/master/test/integration/oss-to-xpack-upgrade.yml) which is testing migration from oss package to basic package.

I adapted it to test migration from basic package to oss package and had a successful deployment on CentOS 7:

```
$ cat << EOF >> test/integration/oss-to-xpack-upgrade.yml
---
- name: Install basic version
  hosts: localhost
  post_tasks:
    - include: elasticsearch/test/integration/debug.yml
  roles:
    - elasticsearch
  vars:
    es_version: "{{ '7.0.0' if es_major_version == '7.x' else '6.7.1' }}" # This is set to an older version than the current default to force an upgrade
    es_enable_xpack: true
    es_heap_size: "1g"
- name: Migrate to oss version
  hosts: localhost
  post_tasks:
    - include: elasticsearch/test/integration/debug.yml
  roles:
    - elasticsearch
  vars:
    es_enable_xpack: false
    es_heap_size: "1g"
EOF

$ make converge PATTERN=oss-to-xpack-upgrade-centos-7 VERSION=7.x
bundle exec kitchen converge oss-to-xpack-upgrade-centos-7
...
       PLAY [Install basic version] *****************
...
       TASK [elasticsearch : RedHat - add Elasticsearch repo] *************************
       changed: [localhost]

       TASK [elasticsearch : RedHat - remove unused Elasticsearch repo] ***************
       ok: [localhost]
...
       TASK [elasticsearch : RedHat - Remove the other elasticsearch package if switching between OSS and standard] ***
       ok: [localhost]
...
       TASK [elasticsearch : RedHat - Install Elasticsearch] **************************
       changed: [localhost]
...
       PLAY [Migrate to oss version] *****************
...
       TASK [elasticsearch : RedHat - add Elasticsearch repo] *************************
       changed: [localhost]

       TASK [elasticsearch : RedHat - remove unused Elasticsearch repo] ***************
       changed: [localhost]
...
       TASK [elasticsearch : RedHat - Remove the other elasticsearch package if switching between OSS and standard] ***
       changed: [localhost]
...
       TASK [elasticsearch : RedHat - Install Elasticsearch] **************************
       changed: [localhost]
...
       PLAY RECAP *********************************************************************
       localhost                  : ok=49   changed=21   unreachable=0    failed=0    skipped=245  rescued=0    ignored=0

       Downloading files from <oss-to-xpack-upgrade-centos-7>
       Finished converging <oss-to-xpack-upgrade-centos-7> (93m58.96s).
-----> Kitchen is finished. (94m3.87s)
```

Also I think it would be better in your case to set `es_enable_xpack=true` to stay with basic package and add features in `es_xpack_features` later when you'll be ready to use them, switching from basic to oss package if you don't use any xpack feature should be successful. 

Can you add your playbook with the deployment logs to detect what is causing failures during the switch basic version to oss version?

**Comment by LukeRoz** [comment]
Oh, about that... I've forgot to mention that now we're using 3rd party security plugin _readOnlyRest_ that's interfering with enabled x-pack, sorry. :)

About deployment: playbook runs fine, no complains about that. My issue is that I cannot perform **rolling upgrade** when switching from basic to oss version. When one of the nodes is switched to oss it cannot rejoin the cluster. In the logs it's clearly visible that oss installation is incompatible with non-oss version (unknown variable `licenses`).
API response from affected node:
```
{
    "error": {
        "root_cause": [
            {
                "type": "master_not_discovered_exception",
                "reason": null
            }
        ],
        "type": "master_not_discovered_exception",
        "reason": null
    },
    "status": 503
}
```
Affected ES node logs:
```
[2019-09-04T09:24:26,301][INFO ][o.e.c.c.JoinHelper       ] [elastic-es-test-2] failed to join {elastic-es-test-1}{GkMmzy7AQ4Ow2nHtTwi7fw}{RiqKG-ewT9GbvVhHiPL24A}{elastic-es-test-1.c.cloud.internal}{x.x.x.208:9300}{ml.machine_memory=15762886656, ml.max_open_jobs=20, xpack.installed=true} with JoinRequest{sourceNode={elastic-es-test-2}{M0QLjCO6QXmzrxnwx0XMQQ}{YTpNnG7wRkyCsR0uYu63vQ}{elastic-es-test-2.c.cloud.internal}{x.x.x.207:9300}, optionalJoin=Optional.empty}
org.elasticsearch.transport.RemoteTransportException: [elastic-es-test-1][x.x.x.208:9300][internal:cluster/coordination/join]
Caused by: java.lang.IllegalStateException: failure when sending a validation request to node
        at org.elasticsearch.cluster.coordination.Coordinator$3.onFailure(Coordinator.java:500) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.coordination.JoinHelper$5.handleException(JoinHelper.java:359) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1124) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.transport.TcpTransport.lambda$handleException$24(TcpTransport.java:1001) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) ~[elasticsearch-7.1.1.jar:7.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: org.elasticsearch.transport.RemoteTransportException: [elastic-es-test-2][x.x.x.207:9300][internal:cluster/coordination/join/validate]
Caused by: java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.cluster.metadata.MetaData$Custom][licenses]
        at org.elasticsearch.common.io.stream.NamedWriteableRegistry.getReader(NamedWriteableRegistry.java:112) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:45) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:39) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.metadata.MetaData.readFrom(MetaData.java:913) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.ClusterState.readFrom(ClusterState.java:796) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.coordination.ValidateJoinRequest.readFrom(ValidateJoinRequest.java:40) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.io.stream.Streamable.lambda$newWriteableReader$0(Streamable.java:51) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.transport.RequestHandlerRegistry.newRequest(RequestHandlerRegistry.java:56) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1032) [elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:922) [elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:753) [elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:53) [transport-netty4-client-7.1.1.jar:7.1.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [netty-handler-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [netty-common-4.1.32.Final.jar:4.1.32.Final]
        at java.lang.Thread.run(Thread.java:835) ~[?:?]
```

**Comment by jmlrt** [comment]
Thank you for the details and logs about oss node not joining cluster during basic to oss rolling upgrade. We'll do more tests and see if that's an expected behavior and if we need to update doc or fix it.

**Comment by jmlrt** [comment]
> Why don't you set es_enable_xpack=true? You should have some 7.1.1 basic installation and as long as es_xpack_features and authentication related variables (es_users, es_roles, es_api_basic_auth_username & es_api_basic_auth_password) are empty, you won't have any impacts.

After some verification, having `es_xpack_features` empty is now installing default xpack features so that won't be relevant for you.

**Comment by jmlrt** [comment]
OK after digging for a few hours into Elasticsearch documentation and Ansible code:

Since Elasticsearch 6.3, by default, when you install Elasticsearch, X-Pack is installed (except if you install oss package) (source: https://www.elastic.co/guide/en/elasticsearch/reference/7.1/setup-xpack.html).

There is no way to uninstall X-Pack (source: https://discuss.elastic.co/t/how-can-i-disable-or-uninstall-x-pack-in-elk-stack-version-6-7/175339/2)

If you are not using oss package, the only control that you have on X-Pack features is by enabling or disabling certain specific features in Elasticsearch configuration with `xpack.<FEATURE>.enabled: false`

This setting is available for `monitoring` or `security` for example.

Our `es_xpack_features` variable is broken as it doesn't allow us to select X-Pack features to install anymore and we'll need to address that in another ticket.

Regarding your use case, if you already have Elasticsearch > 6.2 with non oss package, you should already have X-Pack enabled and the upgrade shouldn't have any impact as long as you keep `es_enable_xpack=true`.

Regarding `readonlyrest` plugin interfering with X-Pack, I suspect that disabling security feature with `xpack.security.enabled: false` should be enough.

If you currently have Elasticsearch <= 6.2, then 6.3 was already a breaking change with the integration of X-Pack inside Elasticsearch non oss package and I'm afraid you won't be able to upgrade without any downtime with this ansible role.

**Comment by LukeRoz** [comment]
Those variable names are somewhat misleading... `es_xpack_features` used as a switch between oss and basic versions confused me a little. But I agree that fixing `es_xpack_features` is way better solution than my approach.

Thank you for your help :)
